# Generated by Django 5.0.2 on 2024-11-30 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hex_colour', models.CharField(max_length=9)),
                ('points_required', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.TextField(primary_key=True, serialize=False)),
                ('global_blacklist', models.BooleanField()),
                ('global_whitelist', models.BooleanField()),
                ('item_blacklist', models.ManyToManyField(related_name='blacklisted_for_items', to='tagme.item')),
                ('item_whitelist', models.ManyToManyField(related_name='whitelisted_for_items', to='tagme.item')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('global_blacklist', 'Global Blacklist'), ('item_blacklist', 'Item Blacklist'), ('global_whitelist', 'Global Whitelist'), ('item_whitelist', 'Item Whitelist')], max_length=16)),
                ('decision_datetime', models.DateTimeField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagme.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagme.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=True)),
                ('comment', models.TextField(null=True)),
                ('comment_datetime', models.DateTimeField(null=True)),
                ('item_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tagme.item')),
                ('private_tags', models.ManyToManyField(related_name='private_tags', to='tagme.tag')),
                ('public_tags', models.ManyToManyField(related_name='public_tags', to='tagme.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveBigIntegerField(default=0)),
                ('equipped_title_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_1', to='tagme.reward')),
                ('equipped_title_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_2', to='tagme.reward')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usercontribution',
            constraint=models.UniqueConstraint(fields=('user_id', 'item_id'), name='unique_user_contribution'),
        ),
    ]
