# pylint: skip-file
# Generated by Django 5.0.2 on 2024-12-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontribution',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
