# Generated by Django 5.0.2 on 2024-11-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_title_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_1', to='tagme.reward'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_title_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_2', to='tagme.reward'),
        ),
    ]
