# pylint: skip-file
# Generated by Django 5.0.2 on 2024-12-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0002_usercontribution_points_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='decision',
            field=models.CharField(blank=True, choices=[('global_blacklist', 'Global Blacklist'), ('item_blacklist', 'Item Blacklist'), ('global_whitelist', 'Global Whitelist'), ('item_whitelist', 'Item Whitelist'), ('ignore_report', 'Ignore Report')], max_length=16, null=True),
        ),
    ]
