# Generated by Django 5.0.2 on 2024-11-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0002_alter_userprofile_equipped_title_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontribution',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tag',
            name='global_blacklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='global_whitelist',
            field=models.BooleanField(default=False),
        ),
    ]
