# Generated by Django 5.0.2 on 2024-11-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0003_rename_user_id_usercontribution_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontribution',
            old_name='item_id',
            new_name='item',
        ),
    ]
