# Generated by Django 5.0.2 on 2024-11-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0004_rename_item_id_usercontribution_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='item_blacklist',
            field=models.ManyToManyField(default=None, related_name='blacklisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='item_whitelist',
            field=models.ManyToManyField(default=None, related_name='whitelisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tagme.item'),
        ),
    ]
