# Generated by Django 5.0.2 on 2025-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0005_usercontribution_pin_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
