# Generated by Django 5.0.2 on 2024-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0005_alter_tag_item_blacklist_alter_tag_item_whitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='decision',
            field=models.CharField(blank=True, choices=[('global_blacklist', 'Global Blacklist'), ('item_blacklist', 'Item Blacklist'), ('global_whitelist', 'Global Whitelist'), ('item_whitelist', 'Item Whitelist')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='decision_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='item_blacklist',
            field=models.ManyToManyField(blank=True, null=True, related_name='blacklisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='item_whitelist',
            field=models.ManyToManyField(blank=True, null=True, related_name='whitelisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='comment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
