# Generated by Django 5.0.2 on 2024-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0006_alter_report_decision_alter_report_decision_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='item_blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='item_whitelist',
            field=models.ManyToManyField(blank=True, related_name='whitelisted_for_items', to='tagme.item'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='private_tags',
            field=models.ManyToManyField(blank=True, related_name='private_tags', to='tagme.tag'),
        ),
        migrations.AlterField(
            model_name='usercontribution',
            name='public_tags',
            field=models.ManyToManyField(blank=True, related_name='public_tags', to='tagme.tag'),
        ),
    ]
