# Generated by Django 5.0.2 on 2024-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagme', '0007_alter_tag_item_blacklist_alter_tag_item_whitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontribution',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
